package openapi

import (
	"fmt"
	"net/http"

	openapiMusic "mikromolekula2002/music_library_ver1.0/apiAutoGenerated/MusicInfo"
)

func MakeMusicAPIClient(MusicAPIHost, MusicBaseURL string) *openapiMusic.APIClient {
	musicAPIConfig := &openapiMusic.Configuration{
		Host:   MusicAPIHost,
		Scheme: "http",
		Servers: openapiMusic.ServerConfigurations{
			{
				URL:         MusicBaseURL,
				Description: "music-info",
			},
		},
		HTTPClient: &http.Client{},
	}

	fmt.Println("BASE URL: ", MusicBaseURL) ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	fmt.Println("API HOST: ", MusicAPIHost)

	return openapiMusic.NewAPIClient(musicAPIConfig)
}
